name: Generate ASCII Art

on: 
    push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Repository Files
        run: ls -ltra

      - name: Executinng Shell Script
        run: ./ascii-script.sh
            

