name: Matrix Configuration

on: 
   push:
   workflow_dispatch:

jobs:
    deploy:
        strategy:
         fail-fast: false
         max-parallel: 2
         matrix:
            os: [ubuntu-latest, ubuntu-20.04, windows-latest]
            image: [hello-world, alpine]
            exclude:
                - image: alpine
                  os: windows-latest
            include:
                - image: amd64/alpine
                  os: ubuntu-20.04
        runs-on: ${{ matrix.os }}
        steps:
            - name: Echo Docker Details
              run: docker info
    
            - name: Run Images on ${{ matrix.os }}
              run: docker run ${{ matrix.image }}
